[package]
name = "actix-web-middleware-keycloak-auth"
version = "0.4.0-beta.2"
authors = ["David Sferruzza <david.sferruzza@gmail.com>"]
edition = "2021"
description = "A middleware for Actix Web that handles authentication with a JWT emitted by Keycloak"
repository = "https://github.com/dsferruzza/actix-web-middleware-keycloak-auth"
readme = "README.md"
documentation = "https://docs.rs/actix-web-middleware-keycloak-auth"
categories = ["authentication", "web-programming::http-server"]
keywords = ["actix-web", "middleware", "authentication", "jwt", "keycloak"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.0.0-beta.21", default-features = false }
chrono = { version = "0.4.19", features = ["serde"] }
futures-util = { version = "0.3.19", default-features = false, features = ["std"] }
log = "0.4.14"
jsonwebtoken = "7.2.0"
serde = { version = "1.0.135", features = ["derive"] }
serde_json = "1.0.78"
uuid = { version = "0.8.2", features = ["serde"] }
paperclip = { git = "https://github.com/sfisol/paperclip", version = "0.6.1", rev = "99db92949e95287fbeb8f3ea844291f1810cccee", features = ["actix"], optional = true } # we depend on a fork until paperclip supports actix-web 4; see https://github.com/wafflespeanut/paperclip/pull/314

[dev-dependencies]
env_logger = "0.9.0"
uuid = { version = "0.8.2", features = ["serde", "v4"] }

[features]
default = []
paperclip_compat = ["paperclip"]
