[package]
name = "actix-web-middleware-keycloak-auth"
version = "0.3.0"
authors = ["David Sferruzza <david.sferruzza@gmail.com>"]
edition = "2018"
description = "A middleware for Actix Web that handles authentication with a JWT emitted by Keycloak"
repository = "https://github.com/dsferruzza/actix-web-middleware-keycloak-auth"
readme = "README.md"
documentation = "https://docs.rs/actix-web-middleware-keycloak-auth"
categories = ["authentication", "web-programming::http-server"]
keywords = ["actix-web", "middleware", "authentication", "jwt", "keycloak"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-beta.4"
chrono = { version = "0.4.19", features = ["serde"] }
futures-util = "0.3.13"
log = "0.4.14"
jsonwebtoken = "7.2.0"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
uuid = { version = "0.8.2", features = ["serde"] }

[dev-dependencies]
actix-rt = "2.1.0"
env_logger = "0.8.3"
uuid = { version = "0.8.2", features = ["serde", "v4"] }
